log:
  level: info
db:
  user: root
  password: ""
  host: "127.0.0.1"
  port: 3333
k8s:
  in-cluster: false
  config-path: /Users/tatsuya.atsumi/go/jobnetes/src/github.com/Attsun1031/jobnetes/cmd/example/config
  master-url: "https://192.168.99.100:8443"
