apiVersion: batch/v1
kind: Job
metadata:
  name: jobnetes-api-client-example-record-task-output
spec:
  template:
    spec:
      containers:
      - name: jobnetes-api-client-example-record-task-output
        image: attsun/jobnetes-api-client-example-record-task-output:latest
        args: ["-endpoint", "jobnetes-api-server:50051", "-task-id", "1"]
      restartPolicy: Never
  backoffLimit: 1
