apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobnetes-api-server
spec:
  selector:
    matchLabels:
      app: jobnetes-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: jobnetes-api-server
    spec:
      containers:
      - name: jobnetes-api-server
        image: attsun/jobnetes-api-server:latest
        ports:
        - containerPort: 50051
