apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jobnetes-manager
spec:
  selector:
    matchLabels:
      app: jobnetes-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: jobnetes-manager
    spec:
      containers:
      - name: jobnetes-manager
        image: attsun/jobnetes-manager:latest
